SELECT * FROM TELEFONES;
SELECT * FROM associados;
SELECT * FROM AUTORES;
SELECT * FROM EDITORAS;
SELECT * FROM LIVROS;
SELECT * FROM EXEMPLARES;
SELECT * FROM EMPRESTIMO_EXEMPLARES;
SELECT * FROM EMPRESTIMOS;
