CREATE SCHEMA IF NOT EXISTS `LEITURA` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `LEITURA` ;

-- -----------------------------------------------------
-- Table `LEITURA`.`ASSOCIADOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LEITURA`.`ASSOCIADOS` (
  `ID_ASSOCIADO` INT NOT NULL AUTO_INCREMENT,
  `RG` CHAR(7) NOT NULL,
  `NOME` VARCHAR(50) NOT NULL,
  `SOBRENOME` VARCHAR(50) NULL,
  `ENDERECO` VARCHAR(150) NULL,
  `CIDADE` VARCHAR(50) NULL,
  `ESTADO` VARCHAR(2) NULL,
  PRIMARY KEY (`ID_ASSOCIADO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LEITURA`.`TELEFONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LEITURA`.`TELEFONES` (
  `ID_TELEFONE` INT NOT NULL AUTO_INCREMENT,
  `TELEFONE_SOCIO` VARCHAR(100) NULL,
  `ID_ASSOCIADO` INT NOT NULL,
  PRIMARY KEY (`ID_TELEFONE`),
  INDEX `FK_TELEFONES_ASSOCIADOS_idx` (`ID_ASSOCIADO` ASC) VISIBLE,
  CONSTRAINT `FK_TELEFONES_ASSOCIADOS`
    FOREIGN KEY (`ID_ASSOCIADO`)
    REFERENCES `LEITURA`.`ASSOCIADOS` (`ID_ASSOCIADO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LEITURA`.`AUTORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LEITURA`.`AUTORES` (
  `ID_AUTOR` INT NOT NULL AUTO_INCREMENT,
  `SOBRENOME` VARCHAR(100) NULL,
  `NOME` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID_AUTOR`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LEITURA`.`EDITORAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LEITURA`.`EDITORAS` (
  `ID_EDITORA` INT NOT NULL AUTO_INCREMENT,
  `RAZAO_SOCIAL` VARCHAR(150) NOT NULL,
  `TELEFONE` VARCHAR(100) NULL,
  PRIMARY KEY (`ID_EDITORA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LEITURA`.`LIVROS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LEITURA`.`LIVROS` (
  `ID_LIVRO` INT NOT NULL AUTO_INCREMENT,
  `COD_ISBN` VARCHAR(13) NULL,
  `TITULO` VARCHAR(200) NOT NULL,
  `ANO_CRIACAO` YEAR(4) NULL,
  `ID_AUTOR` INT NOT NULL,
  `ANO_PUBLICACAO` YEAR(4) NULL,
  `ID_EDITORA` INT NULL,
  INDEX `FK_AUTORES_LIVROS_idx` (`ID_AUTOR` ASC) VISIBLE,
  INDEX `FK_LIVROS_EDITORAS_idx` (`ID_EDITORA` ASC) VISIBLE,
  PRIMARY KEY (`ID_LIVRO`),
  CONSTRAINT `FK_AUTORES_LIVROS`
    FOREIGN KEY (`ID_AUTOR`)
    REFERENCES `LEITURA`.`AUTORES` (`ID_AUTOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_LIVROS_EDITORAS`
    FOREIGN KEY (`ID_EDITORA`)
    REFERENCES `LEITURA`.`EDITORAS` (`ID_EDITORA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LEITURA`.`EMPRESTIMOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LEITURA`.`EMPRESTIMOS` (
  `ID_EMPRESTIMO` INT NOT NULL AUTO_INCREMENT,
  `ID_ASSOCIADO` INT NOT NULL,
  `DATA` DATE NOT NULL,
  `PRAZO_DEVOLUCAO` DATE NULL,
  `DATA_DEVOLUCAO` DATE NULL,
  PRIMARY KEY (`ID_EMPRESTIMO`),
  INDEX `FK_EMPRESTIMOS_ASSOCIADOS_idx` (`ID_ASSOCIADO` ASC) VISIBLE,
  CONSTRAINT `FK_EMPRESTIMOS_ASSOCIADOS`
    FOREIGN KEY (`ID_ASSOCIADO`)
    REFERENCES `LEITURA`.`ASSOCIADOS` (`ID_ASSOCIADO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LEITURA`.`EXEMPLARES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LEITURA`.`EXEMPLARES` (
  `ID_EXEMPLAR` INT NOT NULL AUTO_INCREMENT,
  `ID_LIVRO` INT NOT NULL,
  `SINISTRO` TINYINT NULL,
  PRIMARY KEY (`ID_EXEMPLAR`),
  INDEX `FK_EXMPLARES_LIVROS_idx` (`ID_LIVRO` ASC) VISIBLE,
  CONSTRAINT `FK_EXEMPLARES_LIVROS`
    FOREIGN KEY (`ID_LIVRO`)
    REFERENCES `LEITURA`.`LIVROS` (`ID_LIVRO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LEITURA`.`EMPRESTIMO_EXEMPLARES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LEITURA`.`EMPRESTIMO_EXEMPLARES` (
  `ID_EMPRESTIMO_EXEMPLAR` INT NOT NULL AUTO_INCREMENT,
  `ID_EMPRESTIMO` INT NOT NULL,
  `ID_EXEMPLAR` INT NOT NULL,
  PRIMARY KEY (`ID_EMPRESTIMO_EXEMPLAR`),
  INDEX `FK_EMP_EXEMP_EMPRESTIMOS_idx` (`ID_EMPRESTIMO` ASC) VISIBLE,
  INDEX `FK_EMP_EXEMP_EXEMPLARES_idx` (`ID_EXEMPLAR` ASC) VISIBLE,
  CONSTRAINT `FK_EMP_EXEMP_EMPRESTIMOS`
    FOREIGN KEY (`ID_EMPRESTIMO`)
    REFERENCES `LEITURA`.`EMPRESTIMOS` (`ID_EMPRESTIMO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_EMP_EXEMP_EXEMPLARES`
    FOREIGN KEY (`ID_EXEMPLAR`)
    REFERENCES `LEITURA`.`EXEMPLARES` (`ID_EXEMPLAR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;